/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicNewsletterRouteImport } from './routes/_public/newsletter'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOtpRouteImport } from './routes/_authenticated/otp'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as PublicEventsIndexRouteImport } from './routes/_public/events/index'
import { Route as PublicLoginMagicRouteImport } from './routes/_public/login/magic'
import { Route as PublicEventsEventIdRouteImport } from './routes/_public/events/$eventId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicNewsletterRoute = PublicNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOtpRoute = AuthenticatedOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEventsIndexRoute = PublicEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginMagicRoute = PublicLoginMagicRouteImport.update({
  id: '/login/magic',
  path: '/login/magic',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicEventsEventIdRoute = PublicEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/otp': typeof AuthenticatedOtpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/newsletter': typeof PublicNewsletterRoute
  '/register': typeof PublicRegisterRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/login/magic': typeof PublicLoginMagicRoute
  '/events': typeof PublicEventsIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otp': typeof AuthenticatedOtpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/newsletter': typeof PublicNewsletterRoute
  '/register': typeof PublicRegisterRoute
  '/events/$eventId': typeof PublicEventsEventIdRoute
  '/login/magic': typeof PublicLoginMagicRoute
  '/events': typeof PublicEventsIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/otp': typeof AuthenticatedOtpRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_public/newsletter': typeof PublicNewsletterRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/events/$eventId': typeof PublicEventsEventIdRoute
  '/_public/login/magic': typeof PublicLoginMagicRoute
  '/_public/events/': typeof PublicEventsIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/otp'
    | '/profile'
    | '/newsletter'
    | '/register'
    | '/events/$eventId'
    | '/login/magic'
    | '/events'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otp'
    | '/profile'
    | '/newsletter'
    | '/register'
    | '/events/$eventId'
    | '/login/magic'
    | '/events'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/otp'
    | '/_authenticated/profile'
    | '/_public/newsletter'
    | '/_public/register'
    | '/_public/events/$eventId'
    | '/_public/login/magic'
    | '/_public/events/'
    | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/newsletter': {
      id: '/_public/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof PublicNewsletterRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/otp': {
      id: '/_authenticated/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthenticatedOtpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/events/': {
      id: '/_public/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login/magic': {
      id: '/_public/login/magic'
      path: '/login/magic'
      fullPath: '/login/magic'
      preLoaderRoute: typeof PublicLoginMagicRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/events/$eventId': {
      id: '/_public/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof PublicEventsEventIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOtpRoute: typeof AuthenticatedOtpRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOtpRoute: AuthenticatedOtpRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicNewsletterRoute: typeof PublicNewsletterRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicEventsEventIdRoute: typeof PublicEventsEventIdRoute
  PublicLoginMagicRoute: typeof PublicLoginMagicRoute
  PublicEventsIndexRoute: typeof PublicEventsIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicNewsletterRoute: PublicNewsletterRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicEventsEventIdRoute: PublicEventsEventIdRoute,
  PublicLoginMagicRoute: PublicLoginMagicRoute,
  PublicEventsIndexRoute: PublicEventsIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
